[project]
name = "paris-real-estate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "playwright-stealth>=2.0.3",
    "psycopg2-binary>=2.9.13",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "statsmodels>=0.15.0",
]

[dependency-groups]
dev = [
    "pyyaml>=6.0.3",
]
